name: Update Latest Blog Posts

on:
  workflow_dispatch:
  # for trigger via webhooks
  repository_dispatch:
    types: [trigger]

jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: Update Posts

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Posts
        uses: JannikWempe/github-latest-hashnode-posts@main
        with:
          HASHNODE_PUBLICATION_ID: 60841809fea38e52a9c5bd63
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
