name: Update Latest Blog Posts

on:
  schedule:
    # 5:30 and 17:30 every day
    - cron: '30 5,17 * * *'

  workflow_dispatch:
  # for trigger via webhooks
  repository_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: Update Posts

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Posts
        uses: JannikWempe/github-latest-hashnode-posts@main
        with:
          HASHNODE_PUBLICATION_ID: 60841809fea38e52a9c5bd63
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
