name: Update Recent Activity

on:
  schedule:
    # 5:30 and 17:30 every day
    - cron: '30 5,17 * * *'
  workflow_dispatch:

jobs:
  update-activity:
    name: Update Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
